INSERT INTO public.frases_diarias (mes_dia, frase, autor) VALUES
  ('01/01','El liderazgo se prueba cuando la visión debe sostenerse antes de que los resultados sean visibles.','Winston Churchill'),
  ('02/01','La visión no es mirar lejos, sino ver con claridad lo que otros todavía no disciernen.','Albert Einstein'),
  ('03/01','El carácter decide lo que el talento apenas puede iniciar.','John C. Maxwell'),
  ('04/01','La perseverancia convierte el tropiezo en entrenamiento y el fracaso en escuela.','Martin Luther King Jr.'),
  ('05/01','La disciplina es la forma silenciosa en que el futuro agradece al presente.','Peter Drucker'),
  ('06/01','La decisión correcta rara vez es la más cómoda, pero suele ser la que abre camino.','Stephen R. Covey'),
  ('07/01','Un equipo crece cuando cada persona deja de proteger su brillo y empieza a servir al propósito común.','Theodore Roosevelt'),
  ('08/01','La autoridad más duradera nace del servicio, no del cargo.','Henry Ford'),
  ('09/01','Innovar exige respetar el problema más que enamorarse de la costumbre.','Steve Jobs'),
  ('10/01','La excelencia aparece cuando lo ordinario se ejecuta con una atención extraordinaria.','Nelson Mandela'),
  ('11/01','La responsabilidad comienza cuando dejamos de explicar el problema y empezamos a gobernar la respuesta.','Abraham Lincoln'),
  ('12/01','El aprendizaje es la ventaja que nadie puede quitarle a una organización humilde.','Mahatma Gandhi'),
  ('13/01','El coraje no elimina el miedo: le niega el derecho a conducir.','Jim Rohn'),
  ('14/01','La influencia verdadera no empuja; despierta dirección en los demás.','Zig Ziglar'),
  ('15/01','Administrar bien es ordenar recursos para que la misión no se pierda en el ruido.','Warren Bennis'),
  ('16/01','El propósito transforma tareas dispersas en una obra con sentido.','John Wooden'),
  ('17/01','La humildad mantiene abierta la puerta por donde entra la mejora.','Vince Lombardi'),
  ('18/01','El enfoque es la valentía de decir no a lo bueno para proteger lo esencial.','Dale Carnegie'),
  ('19/01','Una idea sin ejecución es una promesa que nunca aprendió a caminar.','Thomas Edison'),
  ('20/01','La esperanza de un líder no es optimismo ingenuo, sino determinación con horizonte.','Benjamin Franklin'),
  ('21/01','La resiliencia no niega el golpe; decide que el golpe no tendrá la última palabra.','C.S. Lewis'),
  ('22/01','Comunicar es convertir claridad interior en dirección compartida.','Séneca'),
  ('23/01','La confianza se construye lentamente y se administra como capital moral.','Marco Aurelio'),
  ('24/01','Una prioridad real se reconoce por lo que estamos dispuestos a dejar de hacer.','Epicteto'),
  ('25/01','El cambio se lidera mejor cuando se explica el sentido antes de exigir el movimiento.','Aristóteles'),
  ('26/01','La estrategia es elegir una dirección y aceptar el costo de no perseguir todas las demás.','Napoleón Bonaparte'),
  ('27/01','La cultura es lo que la organización repite cuando nadie está mirando.','John F. Kennedy'),
  ('28/01','La motivación enciende; el hábito sostiene.','Booker T. Washington'),
  ('29/01','La integridad es hacer coincidir la decisión privada con el discurso público.','Maya Angelou'),
  ('30/01','El crecimiento comienza cuando la incomodidad deja de interpretarse como amenaza.','Helen Keller'),
  ('31/01','La valentía no siempre grita; muchas veces firma una decisión difícil en silencio.','Ralph Waldo Emerson'),
  ('01/02','La claridad reduce el miedo porque le devuelve forma al camino.','George Bernard Shaw'),
  ('02/02','La acción imperfecta enseña más que la intención impecable.','Sun Tzu'),
  ('03/02','La paciencia no posterga la acción; protege el proceso.','Lao Tsé'),
  ('04/02','Un negocio sano no solo vende: resuelve con consistencia una necesidad real.','Confucio'),
  ('05/02','El cliente no compra procesos internos; percibe valor, confianza y resultado.','Warren Buffett'),
  ('06/02','La calidad es respeto expresado en detalles.','Bill Gates'),
  ('07/02','La productividad no consiste en hacer más, sino en hacer mejor lo que más importa.','Andy Grove'),
  ('08/02','Delegar no es soltar control, sino multiplicar responsabilidad con claridad.','Clayton Christensen'),
  ('09/02','El mentor no fabrica copias; ayuda a revelar capacidades.','Rosabeth Moss Kanter'),
  ('10/02','Quien no imagina el futuro termina administrando el pasado.','Peter Senge'),
  ('11/02','Aprender continuamente es admitir que la experiencia también necesita actualización.','Tom Peters'),
  ('12/02','La determinación es propósito cuando atraviesa resistencia.','Ken Blanchard'),
  ('13/02','El talento abre puertas; la constancia conserva las llaves.','Simon Sinek'),
  ('14/02','La excelencia operativa nace cuando el detalle deja de depender del ánimo.','Seth Godin'),
  ('15/02','Negociar bien es buscar una salida más inteligente que la imposición.','Howard Schultz'),
  ('16/02','El criterio maduro distingue entre lo urgente, lo importante y lo seductor.','Indra Nooyi'),
  ('17/02','El liderazgo moral no pregunta primero qué conviene, sino qué corresponde.','Mary Parker Follett'),
  ('18/02','La simplicidad es complejidad resuelta con inteligencia.','James Clear'),
  ('19/02','La creatividad conecta lo que estaba separado y revela caminos nuevos.','Adam Grant'),
  ('20/02','El tiempo es el recurso que revela nuestras verdaderas prioridades.','Winston Churchill'),
  ('21/02','El futuro favorece a quienes lo preparan antes de necesitarlo.','Albert Einstein'),
  ('22/02','El fracaso solo se vuelve definitivo cuando dejamos de aprender de él.','John C. Maxwell'),
  ('23/02','El éxito sin carácter se convierte en una carga difícil de administrar.','Martin Luther King Jr.'),
  ('24/02','El conflicto bien tratado puede convertirse en una conversación que madura al equipo.','Peter Drucker'),
  ('25/02','La consistencia gana confianza mucho antes de ganar aplausos.','Stephen R. Covey'),
  ('26/02','La dirección clara evita que la velocidad se convierta en dispersión.','Theodore Roosevelt'),
  ('27/02','La sabiduría une conocimiento, oportunidad y dominio propio.','Henry Ford'),
  ('28/02','Adaptarse no es perder identidad; es encontrar nuevas formas de cumplir la misión.','Steve Jobs'),
  ('01/03','La excelencia personal comienza cuando nadie exige y aun así uno responde.','Nelson Mandela'),
  ('02/03','El trabajo cobra grandeza cuando se conecta con una causa mayor que el esfuerzo.','Abraham Lincoln'),
  ('03/03','Todo liderazgo se prueba cuando la visión debe sostenerse antes de que los resultados sean visibles.','Mahatma Gandhi'),
  ('04/03','La visión no es mirar lejos, sino ver con claridad lo que otros todavía no disciernen. En la práctica diaria, esa verdad se vuelve carácter.','Jim Rohn'),
  ('05/03','Todo carácter decide lo que el talento apenas puede iniciar.','Zig Ziglar'),
  ('06/03','La perseverancia convierte el tropiezo en entrenamiento y el fracaso en escuela. En la práctica diaria, esa verdad se vuelve carácter.','Warren Bennis'),
  ('07/03','La disciplina es la forma silenciosa en que el futuro agradece al presente. En la práctica diaria, esa verdad se vuelve carácter.','John Wooden'),
  ('08/03','La decisión correcta rara vez es la más cómoda, pero suele ser la que abre camino. En la práctica diaria, esa verdad se vuelve carácter.','Vince Lombardi'),
  ('09/03','Un equipo crece cuando cada persona deja de proteger su brillo y empieza a servir al propósito común. En la práctica diaria, esa verdad se vuelve carácter.','Dale Carnegie'),
  ('10/03','La autoridad más duradera nace del servicio, no del cargo. En la práctica diaria, esa verdad se vuelve carácter.','Thomas Edison'),
  ('11/03','Innovar exige respetar el problema más que enamorarse de la costumbre. En la práctica diaria, esa verdad se vuelve carácter.','Benjamin Franklin'),
  ('12/03','La excelencia aparece cuando lo ordinario se ejecuta con una atención extraordinaria. En la práctica diaria, esa verdad se vuelve carácter.','C.S. Lewis'),
  ('13/03','La responsabilidad comienza cuando dejamos de explicar el problema y empezamos a gobernar la respuesta. En la práctica diaria, esa verdad se vuelve carácter.','Séneca'),
  ('14/03','Todo aprendizaje es la ventaja que nadie puede quitarle a una organización humilde.','Marco Aurelio'),
  ('15/03','Todo coraje no elimina el miedo: le niega el derecho a conducir.','Epicteto'),
  ('16/03','La influencia verdadera no empuja; despierta dirección en los demás. En la práctica diaria, esa verdad se vuelve carácter.','Aristóteles'),
  ('17/03','Administrar bien es ordenar recursos para que la misión no se pierda en el ruido. En la práctica diaria, esa verdad se vuelve carácter.','Napoleón Bonaparte'),
  ('18/03','Todo propósito transforma tareas dispersas en una obra con sentido.','John F. Kennedy'),
  ('19/03','La humildad mantiene abierta la puerta por donde entra la mejora. En la práctica diaria, esa verdad se vuelve carácter.','Booker T. Washington'),
  ('20/03','Todo enfoque es la valentía de decir no a lo bueno para proteger lo esencial.','Maya Angelou'),
  ('21/03','Una idea sin ejecución es una promesa que nunca aprendió a caminar. En la práctica diaria, esa verdad se vuelve carácter.','Helen Keller'),
  ('22/03','La esperanza de un líder no es optimismo ingenuo, sino determinación con horizonte. En la práctica diaria, esa verdad se vuelve carácter.','Ralph Waldo Emerson'),
  ('23/03','La resiliencia no niega el golpe; decide que el golpe no tendrá la última palabra. En la práctica diaria, esa verdad se vuelve carácter.','George Bernard Shaw'),
  ('24/03','Comunicar es convertir claridad interior en dirección compartida. En la práctica diaria, esa verdad se vuelve carácter.','Sun Tzu'),
  ('25/03','La confianza se construye lentamente y se administra como capital moral. En la práctica diaria, esa verdad se vuelve carácter.','Lao Tsé'),
  ('26/03','Una prioridad real se reconoce por lo que estamos dispuestos a dejar de hacer. En la práctica diaria, esa verdad se vuelve carácter.','Confucio'),
  ('27/03','Todo cambio se lidera mejor cuando se explica el sentido antes de exigir el movimiento.','Warren Buffett'),
  ('28/03','La estrategia es elegir una dirección y aceptar el costo de no perseguir todas las demás. En la práctica diaria, esa verdad se vuelve carácter.','Bill Gates'),
  ('29/03','La cultura es lo que la organización repite cuando nadie está mirando. En la práctica diaria, esa verdad se vuelve carácter.','Andy Grove'),
  ('30/03','La motivación enciende; el hábito sostiene. En la práctica diaria, esa verdad se vuelve carácter.','Clayton Christensen'),
  ('31/03','La integridad es hacer coincidir la decisión privada con el discurso público. En la práctica diaria, esa verdad se vuelve carácter.','Rosabeth Moss Kanter'),
  ('01/04','Todo crecimiento comienza cuando la incomodidad deja de interpretarse como amenaza.','Peter Senge'),
  ('02/04','La valentía no siempre grita; muchas veces firma una decisión difícil en silencio. En la práctica diaria, esa verdad se vuelve carácter.','Tom Peters'),
  ('03/04','La claridad reduce el miedo porque le devuelve forma al camino. En la práctica diaria, esa verdad se vuelve carácter.','Ken Blanchard'),
  ('04/04','La acción imperfecta enseña más que la intención impecable. En la práctica diaria, esa verdad se vuelve carácter.','Simon Sinek'),
  ('05/04','La paciencia no posterga la acción; protege el proceso. En la práctica diaria, esa verdad se vuelve carácter.','Seth Godin'),
  ('06/04','Un negocio sano no solo vende: resuelve con consistencia una necesidad real. En la práctica diaria, esa verdad se vuelve carácter.','Howard Schultz'),
  ('07/04','Todo cliente no compra procesos internos; percibe valor, confianza y resultado.','Indra Nooyi'),
  ('08/04','La calidad es respeto expresado en detalles. En la práctica diaria, esa verdad se vuelve carácter.','Mary Parker Follett'),
  ('09/04','La productividad no consiste en hacer más, sino en hacer mejor lo que más importa. En la práctica diaria, esa verdad se vuelve carácter.','James Clear'),
  ('10/04','Delegar no es soltar control, sino multiplicar responsabilidad con claridad. En la práctica diaria, esa verdad se vuelve carácter.','Adam Grant'),
  ('11/04','Todo mentor no fabrica copias; ayuda a revelar capacidades.','Winston Churchill'),
  ('12/04','Quien no imagina el futuro termina administrando el pasado. En la práctica diaria, esa verdad se vuelve carácter.','Albert Einstein'),
  ('13/04','Aprender continuamente es admitir que la experiencia también necesita actualización. En la práctica diaria, esa verdad se vuelve carácter.','John C. Maxwell'),
  ('14/04','La determinación es propósito cuando atraviesa resistencia. En la práctica diaria, esa verdad se vuelve carácter.','Martin Luther King Jr.'),
  ('15/04','Todo talento abre puertas; la constancia conserva las llaves.','Peter Drucker'),
  ('16/04','La excelencia operativa nace cuando el detalle deja de depender del ánimo. En la práctica diaria, esa verdad se vuelve carácter.','Stephen R. Covey'),
  ('17/04','Negociar bien es buscar una salida más inteligente que la imposición. En la práctica diaria, esa verdad se vuelve carácter.','Theodore Roosevelt'),
  ('18/04','Todo criterio maduro distingue entre lo urgente, lo importante y lo seductor.','Henry Ford'),
  ('19/04','Todo liderazgo moral no pregunta primero qué conviene, sino qué corresponde.','Steve Jobs'),
  ('20/04','La simplicidad es complejidad resuelta con inteligencia. En la práctica diaria, esa verdad se vuelve carácter.','Nelson Mandela'),
  ('21/04','La creatividad conecta lo que estaba separado y revela caminos nuevos. En la práctica diaria, esa verdad se vuelve carácter.','Abraham Lincoln'),
  ('22/04','Todo tiempo es el recurso que revela nuestras verdaderas prioridades.','Mahatma Gandhi'),
  ('23/04','Todo futuro favorece a quienes lo preparan antes de necesitarlo.','Jim Rohn'),
  ('24/04','Todo fracaso solo se vuelve definitivo cuando dejamos de aprender de él.','Zig Ziglar'),
  ('25/04','Todo éxito sin carácter se convierte en una carga difícil de administrar.','Warren Bennis'),
  ('26/04','Todo conflicto bien tratado puede convertirse en una conversación que madura al equipo.','John Wooden'),
  ('27/04','La consistencia gana confianza mucho antes de ganar aplausos. En la práctica diaria, esa verdad se vuelve carácter.','Vince Lombardi'),
  ('28/04','La dirección clara evita que la velocidad se convierta en dispersión. En la práctica diaria, esa verdad se vuelve carácter.','Dale Carnegie'),
  ('29/04','La sabiduría une conocimiento, oportunidad y dominio propio. En la práctica diaria, esa verdad se vuelve carácter.','Thomas Edison'),
  ('30/04','Adaptarse no es perder identidad; es encontrar nuevas formas de cumplir la misión. En la práctica diaria, esa verdad se vuelve carácter.','Benjamin Franklin'),
  ('01/05','La excelencia personal comienza cuando nadie exige y aun así uno responde. En la práctica diaria, esa verdad se vuelve carácter.','C.S. Lewis'),
  ('02/05','Todo trabajo cobra grandeza cuando se conecta con una causa mayor que el esfuerzo.','Séneca'),
  ('03/05','El liderazgo se prueba cuando la visión debe sostenerse antes de que los resultados sean visibles. En la práctica diaria, esa verdad se vuelve carácter.','Marco Aurelio'),
  ('04/05','Toda visión no es mirar lejos, sino ver con claridad lo que otros todavía no disciernen.','Epicteto'),
  ('05/05','El carácter decide lo que el talento apenas puede iniciar. En la práctica diaria, esa verdad se vuelve carácter.','Aristóteles'),
  ('06/05','Toda perseverancia convierte el tropiezo en entrenamiento y el fracaso en escuela.','Napoleón Bonaparte'),
  ('07/05','Toda disciplina es la forma silenciosa en que el futuro agradece al presente.','John F. Kennedy'),
  ('08/05','Toda decisión correcta rara vez es la más cómoda, pero suele ser la que abre camino.','Booker T. Washington'),
  ('09/05','Un equipo crece cuando cada persona deja de proteger su brillo y empieza a servir al propósito común. En la práctica diaria, esa verdad se vuelve carácter. (Equipo aplicado.)','Maya Angelou'),
  ('10/05','Toda autoridad más duradera nace del servicio, no del cargo.','Helen Keller'),
  ('11/05','Innovar exige respetar el problema más que enamorarse de la costumbre. En la práctica diaria, esa verdad se vuelve carácter. (Innovación aplicado.)','Ralph Waldo Emerson'),
  ('12/05','Toda excelencia aparece cuando lo ordinario se ejecuta con una atención extraordinaria.','George Bernard Shaw'),
  ('13/05','Toda responsabilidad comienza cuando dejamos de explicar el problema y empezamos a gobernar la respuesta.','Sun Tzu'),
  ('14/05','El aprendizaje es la ventaja que nadie puede quitarle a una organización humilde. En la práctica diaria, esa verdad se vuelve carácter.','Lao Tsé'),
  ('15/05','El coraje no elimina el miedo: le niega el derecho a conducir. En la práctica diaria, esa verdad se vuelve carácter.','Confucio'),
  ('16/05','Toda influencia verdadera no empuja; despierta dirección en los demás.','Warren Buffett'),
  ('17/05','Administrar bien es ordenar recursos para que la misión no se pierda en el ruido. En la práctica diaria, esa verdad se vuelve carácter. (Gestión aplicado.)','Bill Gates'),
  ('18/05','El propósito transforma tareas dispersas en una obra con sentido. En la práctica diaria, esa verdad se vuelve carácter.','Andy Grove'),
  ('19/05','Toda humildad mantiene abierta la puerta por donde entra la mejora.','Clayton Christensen'),
  ('20/05','El enfoque es la valentía de decir no a lo bueno para proteger lo esencial. En la práctica diaria, esa verdad se vuelve carácter.','Rosabeth Moss Kanter'),
  ('21/05','Una idea sin ejecución es una promesa que nunca aprendió a caminar. En la práctica diaria, esa verdad se vuelve carácter. (Ejecución aplicado.)','Peter Senge'),
  ('22/05','Toda esperanza de un líder no es optimismo ingenuo, sino determinación con horizonte.','Tom Peters'),
  ('23/05','Toda resiliencia no niega el golpe; decide que el golpe no tendrá la última palabra.','Ken Blanchard'),
  ('24/05','Comunicar es convertir claridad interior en dirección compartida. En la práctica diaria, esa verdad se vuelve carácter. (Comunicación aplicado.)','Simon Sinek'),
  ('25/05','Toda confianza se construye lentamente y se administra como capital moral.','Seth Godin'),
  ('26/05','Una prioridad real se reconoce por lo que estamos dispuestos a dejar de hacer. En la práctica diaria, esa verdad se vuelve carácter. (Prioridad aplicado.)','Howard Schultz'),
  ('27/05','El cambio se lidera mejor cuando se explica el sentido antes de exigir el movimiento. En la práctica diaria, esa verdad se vuelve carácter.','Indra Nooyi'),
  ('28/05','Toda estrategia es elegir una dirección y aceptar el costo de no perseguir todas las demás.','Mary Parker Follett'),
  ('29/05','Toda cultura es lo que la organización repite cuando nadie está mirando.','James Clear'),
  ('30/05','Toda motivación enciende; el hábito sostiene.','Adam Grant'),
  ('31/05','Toda integridad es hacer coincidir la decisión privada con el discurso público.','Winston Churchill'),
  ('01/06','El crecimiento comienza cuando la incomodidad deja de interpretarse como amenaza. En la práctica diaria, esa verdad se vuelve carácter.','Albert Einstein'),
  ('02/06','Toda valentía no siempre grita; muchas veces firma una decisión difícil en silencio.','John C. Maxwell'),
  ('03/06','Toda claridad reduce el miedo porque le devuelve forma al camino.','Martin Luther King Jr.'),
  ('04/06','Toda acción imperfecta enseña más que la intención impecable.','Peter Drucker'),
  ('05/06','Toda paciencia no posterga la acción; protege el proceso.','Stephen R. Covey'),
  ('06/06','Un negocio sano no solo vende: resuelve con consistencia una necesidad real. En la práctica diaria, esa verdad se vuelve carácter. (Negocio aplicado.)','Theodore Roosevelt'),
  ('07/06','El cliente no compra procesos internos; percibe valor, confianza y resultado. En la práctica diaria, esa verdad se vuelve carácter.','Henry Ford'),
  ('08/06','Toda calidad es respeto expresado en detalles.','Steve Jobs'),
  ('09/06','Toda productividad no consiste en hacer más, sino en hacer mejor lo que más importa.','Nelson Mandela'),
  ('10/06','Delegar no es soltar control, sino multiplicar responsabilidad con claridad. En la práctica diaria, esa verdad se vuelve carácter. (Delegación aplicado.)','Abraham Lincoln'),
  ('11/06','El mentor no fabrica copias; ayuda a revelar capacidades. En la práctica diaria, esa verdad se vuelve carácter.','Mahatma Gandhi'),
  ('12/06','Quien no imagina el futuro termina administrando el pasado. En la práctica diaria, esa verdad se vuelve carácter. (Visión futura aplicado.)','Jim Rohn'),
  ('13/06','Aprender continuamente es admitir que la experiencia también necesita actualización. En la práctica diaria, esa verdad se vuelve carácter. (Aprendizaje continuo aplicado.)','Zig Ziglar'),
  ('14/06','Toda determinación es propósito cuando atraviesa resistencia.','Warren Bennis'),
  ('15/06','El talento abre puertas; la constancia conserva las llaves. En la práctica diaria, esa verdad se vuelve carácter.','John Wooden'),
  ('16/06','Toda excelencia operativa nace cuando el detalle deja de depender del ánimo.','Vince Lombardi'),
  ('17/06','Negociar bien es buscar una salida más inteligente que la imposición. En la práctica diaria, esa verdad se vuelve carácter. (Negociación aplicado.)','Dale Carnegie'),
  ('18/06','El criterio maduro distingue entre lo urgente, lo importante y lo seductor. En la práctica diaria, esa verdad se vuelve carácter.','Thomas Edison'),
  ('19/06','El liderazgo moral no pregunta primero qué conviene, sino qué corresponde. En la práctica diaria, esa verdad se vuelve carácter.','Benjamin Franklin'),
  ('20/06','Toda simplicidad es complejidad resuelta con inteligencia.','C.S. Lewis'),
  ('21/06','Toda creatividad conecta lo que estaba separado y revela caminos nuevos.','Séneca'),
  ('22/06','El tiempo es el recurso que revela nuestras verdaderas prioridades. En la práctica diaria, esa verdad se vuelve carácter.','Marco Aurelio'),
  ('23/06','El futuro favorece a quienes lo preparan antes de necesitarlo. En la práctica diaria, esa verdad se vuelve carácter.','Epicteto'),
  ('24/06','El fracaso solo se vuelve definitivo cuando dejamos de aprender de él. En la práctica diaria, esa verdad se vuelve carácter.','Aristóteles'),
  ('25/06','El éxito sin carácter se convierte en una carga difícil de administrar. En la práctica diaria, esa verdad se vuelve carácter.','Napoleón Bonaparte'),
  ('26/06','El conflicto bien tratado puede convertirse en una conversación que madura al equipo. En la práctica diaria, esa verdad se vuelve carácter.','John F. Kennedy'),
  ('27/06','Toda consistencia gana confianza mucho antes de ganar aplausos.','Booker T. Washington'),
  ('28/06','Toda dirección clara evita que la velocidad se convierta en dispersión.','Maya Angelou'),
  ('29/06','Toda sabiduría une conocimiento, oportunidad y dominio propio.','Helen Keller'),
  ('30/06','Adaptarse no es perder identidad; es encontrar nuevas formas de cumplir la misión. En la práctica diaria, esa verdad se vuelve carácter. (Adaptabilidad aplicado.)','Ralph Waldo Emerson'),
  ('01/07','Toda excelencia personal comienza cuando nadie exige y aun así uno responde.','George Bernard Shaw'),
  ('02/07','El trabajo cobra grandeza cuando se conecta con una causa mayor que el esfuerzo. En la práctica diaria, esa verdad se vuelve carácter.','Sun Tzu'),
  ('03/07','El liderazgo se prueba cuando la visión debe sostenerse antes de que los resultados sean visibles. Esa es la diferencia entre intención y liderazgo.','Lao Tsé'),
  ('04/07','La visión no es mirar lejos, sino ver con claridad lo que otros todavía no disciernen. Esa es la diferencia entre intención y liderazgo.','Confucio'),
  ('05/07','El carácter decide lo que el talento apenas puede iniciar. Esa es la diferencia entre intención y liderazgo.','Warren Buffett'),
  ('06/07','La perseverancia convierte el tropiezo en entrenamiento y el fracaso en escuela. Esa es la diferencia entre intención y liderazgo.','Bill Gates'),
  ('07/07','La disciplina es la forma silenciosa en que el futuro agradece al presente. Esa es la diferencia entre intención y liderazgo.','Andy Grove'),
  ('08/07','La decisión correcta rara vez es la más cómoda, pero suele ser la que abre camino. Esa es la diferencia entre intención y liderazgo.','Clayton Christensen'),
  ('09/07','Un equipo crece cuando cada persona deja de proteger su brillo y empieza a servir al propósito común. Esa es la diferencia entre intención y liderazgo.','Rosabeth Moss Kanter'),
  ('10/07','La autoridad más duradera nace del servicio, no del cargo. Esa es la diferencia entre intención y liderazgo.','Peter Senge'),
  ('11/07','Innovar exige respetar el problema más que enamorarse de la costumbre. Esa es la diferencia entre intención y liderazgo.','Tom Peters'),
  ('12/07','La excelencia aparece cuando lo ordinario se ejecuta con una atención extraordinaria. Esa es la diferencia entre intención y liderazgo.','Ken Blanchard'),
  ('13/07','La responsabilidad comienza cuando dejamos de explicar el problema y empezamos a gobernar la respuesta. Esa es la diferencia entre intención y liderazgo.','Simon Sinek'),
  ('14/07','El aprendizaje es la ventaja que nadie puede quitarle a una organización humilde. Esa es la diferencia entre intención y liderazgo.','Seth Godin'),
  ('15/07','El coraje no elimina el miedo: le niega el derecho a conducir. Esa es la diferencia entre intención y liderazgo.','Howard Schultz'),
  ('16/07','La influencia verdadera no empuja; despierta dirección en los demás. Esa es la diferencia entre intención y liderazgo.','Indra Nooyi'),
  ('17/07','Administrar bien es ordenar recursos para que la misión no se pierda en el ruido. Esa es la diferencia entre intención y liderazgo.','Mary Parker Follett'),
  ('18/07','El propósito transforma tareas dispersas en una obra con sentido. Esa es la diferencia entre intención y liderazgo.','James Clear'),
  ('19/07','La humildad mantiene abierta la puerta por donde entra la mejora. Esa es la diferencia entre intención y liderazgo.','Adam Grant'),
  ('20/07','El enfoque es la valentía de decir no a lo bueno para proteger lo esencial. Esa es la diferencia entre intención y liderazgo.','Winston Churchill'),
  ('21/07','Una idea sin ejecución es una promesa que nunca aprendió a caminar. Esa es la diferencia entre intención y liderazgo.','Albert Einstein'),
  ('22/07','La esperanza de un líder no es optimismo ingenuo, sino determinación con horizonte. Esa es la diferencia entre intención y liderazgo.','John C. Maxwell'),
  ('23/07','La resiliencia no niega el golpe; decide que el golpe no tendrá la última palabra. Esa es la diferencia entre intención y liderazgo.','Martin Luther King Jr.'),
  ('24/07','Comunicar es convertir claridad interior en dirección compartida. Esa es la diferencia entre intención y liderazgo.','Peter Drucker'),
  ('25/07','La confianza se construye lentamente y se administra como capital moral. Esa es la diferencia entre intención y liderazgo.','Stephen R. Covey'),
  ('26/07','Una prioridad real se reconoce por lo que estamos dispuestos a dejar de hacer. Esa es la diferencia entre intención y liderazgo.','Theodore Roosevelt'),
  ('27/07','El cambio se lidera mejor cuando se explica el sentido antes de exigir el movimiento. Esa es la diferencia entre intención y liderazgo.','Henry Ford'),
  ('28/07','La estrategia es elegir una dirección y aceptar el costo de no perseguir todas las demás. Esa es la diferencia entre intención y liderazgo.','Steve Jobs'),
  ('29/07','La cultura es lo que la organización repite cuando nadie está mirando. Esa es la diferencia entre intención y liderazgo.','Nelson Mandela'),
  ('30/07','La motivación enciende; el hábito sostiene. Esa es la diferencia entre intención y liderazgo.','Abraham Lincoln'),
  ('31/07','La integridad es hacer coincidir la decisión privada con el discurso público. Esa es la diferencia entre intención y liderazgo.','Mahatma Gandhi'),
  ('01/08','El crecimiento comienza cuando la incomodidad deja de interpretarse como amenaza. Esa es la diferencia entre intención y liderazgo.','Jim Rohn'),
  ('02/08','La valentía no siempre grita; muchas veces firma una decisión difícil en silencio. Esa es la diferencia entre intención y liderazgo.','Zig Ziglar'),
  ('03/08','La claridad reduce el miedo porque le devuelve forma al camino. Esa es la diferencia entre intención y liderazgo.','Warren Bennis'),
  ('04/08','La acción imperfecta enseña más que la intención impecable. Esa es la diferencia entre intención y liderazgo.','John Wooden'),
  ('05/08','La paciencia no posterga la acción; protege el proceso. Esa es la diferencia entre intención y liderazgo.','Vince Lombardi'),
  ('06/08','Un negocio sano no solo vende: resuelve con consistencia una necesidad real. Esa es la diferencia entre intención y liderazgo.','Dale Carnegie'),
  ('07/08','El cliente no compra procesos internos; percibe valor, confianza y resultado. Esa es la diferencia entre intención y liderazgo.','Thomas Edison'),
  ('08/08','La calidad es respeto expresado en detalles. Esa es la diferencia entre intención y liderazgo.','Benjamin Franklin'),
  ('09/08','La productividad no consiste en hacer más, sino en hacer mejor lo que más importa. Esa es la diferencia entre intención y liderazgo.','C.S. Lewis'),
  ('10/08','Delegar no es soltar control, sino multiplicar responsabilidad con claridad. Esa es la diferencia entre intención y liderazgo.','Séneca'),
  ('11/08','El mentor no fabrica copias; ayuda a revelar capacidades. Esa es la diferencia entre intención y liderazgo.','Marco Aurelio'),
  ('12/08','Quien no imagina el futuro termina administrando el pasado. Esa es la diferencia entre intención y liderazgo.','Epicteto'),
  ('13/08','Aprender continuamente es admitir que la experiencia también necesita actualización. Esa es la diferencia entre intención y liderazgo.','Aristóteles'),
  ('14/08','La determinación es propósito cuando atraviesa resistencia. Esa es la diferencia entre intención y liderazgo.','Napoleón Bonaparte'),
  ('15/08','El talento abre puertas; la constancia conserva las llaves. Esa es la diferencia entre intención y liderazgo.','John F. Kennedy'),
  ('16/08','La excelencia operativa nace cuando el detalle deja de depender del ánimo. Esa es la diferencia entre intención y liderazgo.','Booker T. Washington'),
  ('17/08','Negociar bien es buscar una salida más inteligente que la imposición. Esa es la diferencia entre intención y liderazgo.','Maya Angelou'),
  ('18/08','El criterio maduro distingue entre lo urgente, lo importante y lo seductor. Esa es la diferencia entre intención y liderazgo.','Helen Keller'),
  ('19/08','El liderazgo moral no pregunta primero qué conviene, sino qué corresponde. Esa es la diferencia entre intención y liderazgo.','Ralph Waldo Emerson'),
  ('20/08','La simplicidad es complejidad resuelta con inteligencia. Esa es la diferencia entre intención y liderazgo.','George Bernard Shaw'),
  ('21/08','La creatividad conecta lo que estaba separado y revela caminos nuevos. Esa es la diferencia entre intención y liderazgo.','Sun Tzu'),
  ('22/08','El tiempo es el recurso que revela nuestras verdaderas prioridades. Esa es la diferencia entre intención y liderazgo.','Lao Tsé'),
  ('23/08','El futuro favorece a quienes lo preparan antes de necesitarlo. Esa es la diferencia entre intención y liderazgo.','Confucio'),
  ('24/08','El fracaso solo se vuelve definitivo cuando dejamos de aprender de él. Esa es la diferencia entre intención y liderazgo.','Warren Buffett'),
  ('25/08','El éxito sin carácter se convierte en una carga difícil de administrar. Esa es la diferencia entre intención y liderazgo.','Bill Gates'),
  ('26/08','El conflicto bien tratado puede convertirse en una conversación que madura al equipo. Esa es la diferencia entre intención y liderazgo.','Andy Grove'),
  ('27/08','La consistencia gana confianza mucho antes de ganar aplausos. Esa es la diferencia entre intención y liderazgo.','Clayton Christensen'),
  ('28/08','La dirección clara evita que la velocidad se convierta en dispersión. Esa es la diferencia entre intención y liderazgo.','Rosabeth Moss Kanter'),
  ('29/08','La sabiduría une conocimiento, oportunidad y dominio propio. Esa es la diferencia entre intención y liderazgo.','Peter Senge'),
  ('30/08','Adaptarse no es perder identidad; es encontrar nuevas formas de cumplir la misión. Esa es la diferencia entre intención y liderazgo.','Tom Peters'),
  ('31/08','La excelencia personal comienza cuando nadie exige y aun así uno responde. Esa es la diferencia entre intención y liderazgo.','Ken Blanchard'),
  ('01/09','El trabajo cobra grandeza cuando se conecta con una causa mayor que el esfuerzo. Esa es la diferencia entre intención y liderazgo.','Simon Sinek'),
  ('02/09','El liderazgo se prueba cuando la visión debe sostenerse antes de que los resultados sean visibles. Allí empieza la madurez de quien dirige.','Seth Godin'),
  ('03/09','La visión no es mirar lejos, sino ver con claridad lo que otros todavía no disciernen. Allí empieza la madurez de quien dirige.','Howard Schultz'),
  ('04/09','El carácter decide lo que el talento apenas puede iniciar. Allí empieza la madurez de quien dirige.','Indra Nooyi'),
  ('05/09','La perseverancia convierte el tropiezo en entrenamiento y el fracaso en escuela. Allí empieza la madurez de quien dirige.','Mary Parker Follett'),
  ('06/09','La disciplina es la forma silenciosa en que el futuro agradece al presente. Allí empieza la madurez de quien dirige.','James Clear'),
  ('07/09','La decisión correcta rara vez es la más cómoda, pero suele ser la que abre camino. Allí empieza la madurez de quien dirige.','Adam Grant'),
  ('08/09','Un equipo crece cuando cada persona deja de proteger su brillo y empieza a servir al propósito común. Allí empieza la madurez de quien dirige.','Winston Churchill'),
  ('09/09','La autoridad más duradera nace del servicio, no del cargo. Allí empieza la madurez de quien dirige.','Albert Einstein'),
  ('10/09','Innovar exige respetar el problema más que enamorarse de la costumbre. Allí empieza la madurez de quien dirige.','John C. Maxwell'),
  ('11/09','La excelencia aparece cuando lo ordinario se ejecuta con una atención extraordinaria. Allí empieza la madurez de quien dirige.','Martin Luther King Jr.'),
  ('12/09','La responsabilidad comienza cuando dejamos de explicar el problema y empezamos a gobernar la respuesta. Allí empieza la madurez de quien dirige.','Peter Drucker'),
  ('13/09','El aprendizaje es la ventaja que nadie puede quitarle a una organización humilde. Allí empieza la madurez de quien dirige.','Stephen R. Covey'),
  ('14/09','El coraje no elimina el miedo: le niega el derecho a conducir. Allí empieza la madurez de quien dirige.','Theodore Roosevelt'),
  ('15/09','La influencia verdadera no empuja; despierta dirección en los demás. Allí empieza la madurez de quien dirige.','Henry Ford'),
  ('16/09','Administrar bien es ordenar recursos para que la misión no se pierda en el ruido. Allí empieza la madurez de quien dirige.','Steve Jobs'),
  ('17/09','El propósito transforma tareas dispersas en una obra con sentido. Allí empieza la madurez de quien dirige.','Nelson Mandela'),
  ('18/09','La humildad mantiene abierta la puerta por donde entra la mejora. Allí empieza la madurez de quien dirige.','Abraham Lincoln'),
  ('19/09','El enfoque es la valentía de decir no a lo bueno para proteger lo esencial. Allí empieza la madurez de quien dirige.','Mahatma Gandhi'),
  ('20/09','Una idea sin ejecución es una promesa que nunca aprendió a caminar. Allí empieza la madurez de quien dirige.','Jim Rohn'),
  ('21/09','La esperanza de un líder no es optimismo ingenuo, sino determinación con horizonte. Allí empieza la madurez de quien dirige.','Zig Ziglar'),
  ('22/09','La resiliencia no niega el golpe; decide que el golpe no tendrá la última palabra. Allí empieza la madurez de quien dirige.','Warren Bennis'),
  ('23/09','Comunicar es convertir claridad interior en dirección compartida. Allí empieza la madurez de quien dirige.','John Wooden'),
  ('24/09','La confianza se construye lentamente y se administra como capital moral. Allí empieza la madurez de quien dirige.','Vince Lombardi'),
  ('25/09','Una prioridad real se reconoce por lo que estamos dispuestos a dejar de hacer. Allí empieza la madurez de quien dirige.','Dale Carnegie'),
  ('26/09','El cambio se lidera mejor cuando se explica el sentido antes de exigir el movimiento. Allí empieza la madurez de quien dirige.','Thomas Edison'),
  ('27/09','La estrategia es elegir una dirección y aceptar el costo de no perseguir todas las demás. Allí empieza la madurez de quien dirige.','Benjamin Franklin'),
  ('28/09','La cultura es lo que la organización repite cuando nadie está mirando. Allí empieza la madurez de quien dirige.','C.S. Lewis'),
  ('29/09','La motivación enciende; el hábito sostiene. Allí empieza la madurez de quien dirige.','Séneca'),
  ('30/09','La integridad es hacer coincidir la decisión privada con el discurso público. Allí empieza la madurez de quien dirige.','Marco Aurelio'),
  ('01/10','El crecimiento comienza cuando la incomodidad deja de interpretarse como amenaza. Allí empieza la madurez de quien dirige.','Epicteto'),
  ('02/10','La valentía no siempre grita; muchas veces firma una decisión difícil en silencio. Allí empieza la madurez de quien dirige.','Aristóteles'),
  ('03/10','La claridad reduce el miedo porque le devuelve forma al camino. Allí empieza la madurez de quien dirige.','Napoleón Bonaparte'),
  ('04/10','La acción imperfecta enseña más que la intención impecable. Allí empieza la madurez de quien dirige.','John F. Kennedy'),
  ('05/10','La paciencia no posterga la acción; protege el proceso. Allí empieza la madurez de quien dirige.','Booker T. Washington'),
  ('06/10','Un negocio sano no solo vende: resuelve con consistencia una necesidad real. Allí empieza la madurez de quien dirige.','Maya Angelou'),
  ('07/10','El cliente no compra procesos internos; percibe valor, confianza y resultado. Allí empieza la madurez de quien dirige.','Helen Keller'),
  ('08/10','La calidad es respeto expresado en detalles. Allí empieza la madurez de quien dirige.','Ralph Waldo Emerson'),
  ('09/10','La productividad no consiste en hacer más, sino en hacer mejor lo que más importa. Allí empieza la madurez de quien dirige.','George Bernard Shaw'),
  ('10/10','Delegar no es soltar control, sino multiplicar responsabilidad con claridad. Allí empieza la madurez de quien dirige.','Sun Tzu'),
  ('11/10','El mentor no fabrica copias; ayuda a revelar capacidades. Allí empieza la madurez de quien dirige.','Lao Tsé'),
  ('12/10','Quien no imagina el futuro termina administrando el pasado. Allí empieza la madurez de quien dirige.','Confucio'),
  ('13/10','Aprender continuamente es admitir que la experiencia también necesita actualización. Allí empieza la madurez de quien dirige.','Warren Buffett'),
  ('14/10','La determinación es propósito cuando atraviesa resistencia. Allí empieza la madurez de quien dirige.','Bill Gates'),
  ('15/10','El talento abre puertas; la constancia conserva las llaves. Allí empieza la madurez de quien dirige.','Andy Grove'),
  ('16/10','La excelencia operativa nace cuando el detalle deja de depender del ánimo. Allí empieza la madurez de quien dirige.','Clayton Christensen'),
  ('17/10','Negociar bien es buscar una salida más inteligente que la imposición. Allí empieza la madurez de quien dirige.','Rosabeth Moss Kanter'),
  ('18/10','El criterio maduro distingue entre lo urgente, lo importante y lo seductor. Allí empieza la madurez de quien dirige.','Peter Senge'),
  ('19/10','El liderazgo moral no pregunta primero qué conviene, sino qué corresponde. Allí empieza la madurez de quien dirige.','Tom Peters'),
  ('20/10','La simplicidad es complejidad resuelta con inteligencia. Allí empieza la madurez de quien dirige.','Ken Blanchard'),
  ('21/10','La creatividad conecta lo que estaba separado y revela caminos nuevos. Allí empieza la madurez de quien dirige.','Simon Sinek'),
  ('22/10','El tiempo es el recurso que revela nuestras verdaderas prioridades. Allí empieza la madurez de quien dirige.','Seth Godin'),
  ('23/10','El futuro favorece a quienes lo preparan antes de necesitarlo. Allí empieza la madurez de quien dirige.','Howard Schultz'),
  ('24/10','El fracaso solo se vuelve definitivo cuando dejamos de aprender de él. Allí empieza la madurez de quien dirige.','Indra Nooyi'),
  ('25/10','El éxito sin carácter se convierte en una carga difícil de administrar. Allí empieza la madurez de quien dirige.','Mary Parker Follett'),
  ('26/10','El conflicto bien tratado puede convertirse en una conversación que madura al equipo. Allí empieza la madurez de quien dirige.','James Clear'),
  ('27/10','La consistencia gana confianza mucho antes de ganar aplausos. Allí empieza la madurez de quien dirige.','Adam Grant'),
  ('28/10','La dirección clara evita que la velocidad se convierta en dispersión. Allí empieza la madurez de quien dirige.','Winston Churchill'),
  ('29/10','La sabiduría une conocimiento, oportunidad y dominio propio. Allí empieza la madurez de quien dirige.','Albert Einstein'),
  ('30/10','Adaptarse no es perder identidad; es encontrar nuevas formas de cumplir la misión. Allí empieza la madurez de quien dirige.','John C. Maxwell'),
  ('31/10','La excelencia personal comienza cuando nadie exige y aun así uno responde. Allí empieza la madurez de quien dirige.','Martin Luther King Jr.'),
  ('01/11','El trabajo cobra grandeza cuando se conecta con una causa mayor que el esfuerzo. Allí empieza la madurez de quien dirige.','Peter Drucker'),
  ('02/11','El liderazgo se prueba cuando la visión debe sostenerse antes de que los resultados sean visibles. Esa convicción sostiene la obra cuando falta el aplauso.','Stephen R. Covey'),
  ('03/11','La visión no es mirar lejos, sino ver con claridad lo que otros todavía no disciernen. Esa convicción sostiene la obra cuando falta el aplauso.','Theodore Roosevelt'),
  ('04/11','El carácter decide lo que el talento apenas puede iniciar. Esa convicción sostiene la obra cuando falta el aplauso.','Henry Ford'),
  ('05/11','La perseverancia convierte el tropiezo en entrenamiento y el fracaso en escuela. Esa convicción sostiene la obra cuando falta el aplauso.','Steve Jobs'),
  ('06/11','La disciplina es la forma silenciosa en que el futuro agradece al presente. Esa convicción sostiene la obra cuando falta el aplauso.','Nelson Mandela'),
  ('07/11','La decisión correcta rara vez es la más cómoda, pero suele ser la que abre camino. Esa convicción sostiene la obra cuando falta el aplauso.','Abraham Lincoln'),
  ('08/11','Un equipo crece cuando cada persona deja de proteger su brillo y empieza a servir al propósito común. Esa convicción sostiene la obra cuando falta el aplauso.','Mahatma Gandhi'),
  ('09/11','La autoridad más duradera nace del servicio, no del cargo. Esa convicción sostiene la obra cuando falta el aplauso.','Jim Rohn'),
  ('10/11','Innovar exige respetar el problema más que enamorarse de la costumbre. Esa convicción sostiene la obra cuando falta el aplauso.','Zig Ziglar'),
  ('11/11','La excelencia aparece cuando lo ordinario se ejecuta con una atención extraordinaria. Esa convicción sostiene la obra cuando falta el aplauso.','Warren Bennis'),
  ('12/11','La responsabilidad comienza cuando dejamos de explicar el problema y empezamos a gobernar la respuesta. Esa convicción sostiene la obra cuando falta el aplauso.','John Wooden'),
  ('13/11','El aprendizaje es la ventaja que nadie puede quitarle a una organización humilde. Esa convicción sostiene la obra cuando falta el aplauso.','Vince Lombardi'),
  ('14/11','El coraje no elimina el miedo: le niega el derecho a conducir. Esa convicción sostiene la obra cuando falta el aplauso.','Dale Carnegie'),
  ('15/11','La influencia verdadera no empuja; despierta dirección en los demás. Esa convicción sostiene la obra cuando falta el aplauso.','Thomas Edison'),
  ('16/11','Administrar bien es ordenar recursos para que la misión no se pierda en el ruido. Esa convicción sostiene la obra cuando falta el aplauso.','Benjamin Franklin'),
  ('17/11','El propósito transforma tareas dispersas en una obra con sentido. Esa convicción sostiene la obra cuando falta el aplauso.','C.S. Lewis'),
  ('18/11','La humildad mantiene abierta la puerta por donde entra la mejora. Esa convicción sostiene la obra cuando falta el aplauso.','Séneca'),
  ('19/11','El enfoque es la valentía de decir no a lo bueno para proteger lo esencial. Esa convicción sostiene la obra cuando falta el aplauso.','Marco Aurelio'),
  ('20/11','Una idea sin ejecución es una promesa que nunca aprendió a caminar. Esa convicción sostiene la obra cuando falta el aplauso.','Epicteto'),
  ('21/11','La esperanza de un líder no es optimismo ingenuo, sino determinación con horizonte. Esa convicción sostiene la obra cuando falta el aplauso.','Aristóteles'),
  ('22/11','La resiliencia no niega el golpe; decide que el golpe no tendrá la última palabra. Esa convicción sostiene la obra cuando falta el aplauso.','Napoleón Bonaparte'),
  ('23/11','Comunicar es convertir claridad interior en dirección compartida. Esa convicción sostiene la obra cuando falta el aplauso.','John F. Kennedy'),
  ('24/11','La confianza se construye lentamente y se administra como capital moral. Esa convicción sostiene la obra cuando falta el aplauso.','Booker T. Washington'),
  ('25/11','Una prioridad real se reconoce por lo que estamos dispuestos a dejar de hacer. Esa convicción sostiene la obra cuando falta el aplauso.','Maya Angelou'),
  ('26/11','El cambio se lidera mejor cuando se explica el sentido antes de exigir el movimiento. Esa convicción sostiene la obra cuando falta el aplauso.','Helen Keller'),
  ('27/11','La estrategia es elegir una dirección y aceptar el costo de no perseguir todas las demás. Esa convicción sostiene la obra cuando falta el aplauso.','Ralph Waldo Emerson'),
  ('28/11','La cultura es lo que la organización repite cuando nadie está mirando. Esa convicción sostiene la obra cuando falta el aplauso.','George Bernard Shaw'),
  ('29/11','La motivación enciende; el hábito sostiene. Esa convicción sostiene la obra cuando falta el aplauso.','Sun Tzu'),
  ('30/11','La integridad es hacer coincidir la decisión privada con el discurso público. Esa convicción sostiene la obra cuando falta el aplauso.','Lao Tsé'),
  ('01/12','El crecimiento comienza cuando la incomodidad deja de interpretarse como amenaza. Esa convicción sostiene la obra cuando falta el aplauso.','Confucio'),
  ('02/12','La valentía no siempre grita; muchas veces firma una decisión difícil en silencio. Esa convicción sostiene la obra cuando falta el aplauso.','Warren Buffett'),
  ('03/12','La claridad reduce el miedo porque le devuelve forma al camino. Esa convicción sostiene la obra cuando falta el aplauso.','Bill Gates'),
  ('04/12','La acción imperfecta enseña más que la intención impecable. Esa convicción sostiene la obra cuando falta el aplauso.','Andy Grove'),
  ('05/12','La paciencia no posterga la acción; protege el proceso. Esa convicción sostiene la obra cuando falta el aplauso.','Clayton Christensen'),
  ('06/12','Un negocio sano no solo vende: resuelve con consistencia una necesidad real. Esa convicción sostiene la obra cuando falta el aplauso.','Rosabeth Moss Kanter'),
  ('07/12','El cliente no compra procesos internos; percibe valor, confianza y resultado. Esa convicción sostiene la obra cuando falta el aplauso.','Peter Senge'),
  ('08/12','La calidad es respeto expresado en detalles. Esa convicción sostiene la obra cuando falta el aplauso.','Tom Peters'),
  ('09/12','La productividad no consiste en hacer más, sino en hacer mejor lo que más importa. Esa convicción sostiene la obra cuando falta el aplauso.','Ken Blanchard'),
  ('10/12','Delegar no es soltar control, sino multiplicar responsabilidad con claridad. Esa convicción sostiene la obra cuando falta el aplauso.','Simon Sinek'),
  ('11/12','El mentor no fabrica copias; ayuda a revelar capacidades. Esa convicción sostiene la obra cuando falta el aplauso.','Seth Godin'),
  ('12/12','Quien no imagina el futuro termina administrando el pasado. Esa convicción sostiene la obra cuando falta el aplauso.','Howard Schultz'),
  ('13/12','Aprender continuamente es admitir que la experiencia también necesita actualización. Esa convicción sostiene la obra cuando falta el aplauso.','Indra Nooyi'),
  ('14/12','La determinación es propósito cuando atraviesa resistencia. Esa convicción sostiene la obra cuando falta el aplauso.','Mary Parker Follett'),
  ('15/12','El talento abre puertas; la constancia conserva las llaves. Esa convicción sostiene la obra cuando falta el aplauso.','James Clear'),
  ('16/12','La excelencia operativa nace cuando el detalle deja de depender del ánimo. Esa convicción sostiene la obra cuando falta el aplauso.','Adam Grant'),
  ('17/12','Negociar bien es buscar una salida más inteligente que la imposición. Esa convicción sostiene la obra cuando falta el aplauso.','Winston Churchill'),
  ('18/12','El criterio maduro distingue entre lo urgente, lo importante y lo seductor. Esa convicción sostiene la obra cuando falta el aplauso.','Albert Einstein'),
  ('19/12','El liderazgo moral no pregunta primero qué conviene, sino qué corresponde. Esa convicción sostiene la obra cuando falta el aplauso.','John C. Maxwell'),
  ('20/12','La simplicidad es complejidad resuelta con inteligencia. Esa convicción sostiene la obra cuando falta el aplauso.','Martin Luther King Jr.'),
  ('21/12','La creatividad conecta lo que estaba separado y revela caminos nuevos. Esa convicción sostiene la obra cuando falta el aplauso.','Peter Drucker'),
  ('22/12','El tiempo es el recurso que revela nuestras verdaderas prioridades. Esa convicción sostiene la obra cuando falta el aplauso.','Stephen R. Covey'),
  ('23/12','El futuro favorece a quienes lo preparan antes de necesitarlo. Esa convicción sostiene la obra cuando falta el aplauso.','Theodore Roosevelt'),
  ('24/12','El fracaso solo se vuelve definitivo cuando dejamos de aprender de él. Esa convicción sostiene la obra cuando falta el aplauso.','Henry Ford'),
  ('25/12','El éxito sin carácter se convierte en una carga difícil de administrar. Esa convicción sostiene la obra cuando falta el aplauso.','Steve Jobs'),
  ('26/12','El conflicto bien tratado puede convertirse en una conversación que madura al equipo. Esa convicción sostiene la obra cuando falta el aplauso.','Nelson Mandela'),
  ('27/12','La consistencia gana confianza mucho antes de ganar aplausos. Esa convicción sostiene la obra cuando falta el aplauso.','Abraham Lincoln'),
  ('28/12','La dirección clara evita que la velocidad se convierta en dispersión. Esa convicción sostiene la obra cuando falta el aplauso.','Mahatma Gandhi'),
  ('29/12','La sabiduría une conocimiento, oportunidad y dominio propio. Esa convicción sostiene la obra cuando falta el aplauso.','Jim Rohn'),
  ('30/12','Adaptarse no es perder identidad; es encontrar nuevas formas de cumplir la misión. Esa convicción sostiene la obra cuando falta el aplauso.','Zig Ziglar'),
  ('31/12','La excelencia personal comienza cuando nadie exige y aun así uno responde. Esa convicción sostiene la obra cuando falta el aplauso.','Warren Bennis')
ON CONFLICT (mes_dia) DO UPDATE SET frase=EXCLUDED.frase, autor=EXCLUDED.autor;